# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Vassar MarketPlace' do

 # Add Parse pods and install
 	pod 'Parse'
 	pod 'AlamofireImage'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vassar MarketPlace

  target 'Vassar MarketPlaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Vassar MarketPlaceUITests' do
    # Pods for testing
  end

end
